### ISSUE TITLE
support es6

### ISSUE THREAD

**Issue by sensoroDj** [es-analysis/plato#184]
support ES6 ! It will be amazing!

**Comment by marcofranssen** [comment]
+1

Since node 6 is released, node will support 93% off es6 features.

Currently I'm running node 4 using babeljs transpile.

However for the analysis I do not want to analyze my transpiled files. I want to analyze the original es6 source files.

**Comment by thalesfsp** [comment]
Ref.: https://github.com/es-analysis/plato/pull/153

**Comment by abhipanda** [comment]
I know this is an old thread but do we have any progress on this ? Thanks

**Comment by jsoverson** [comment]
@abhipanda this project is unmaintained. There is a V2 nearly complete on a branch with es6 support but I don't want to push it past the finish line because I will immediately not be able to maintain it and don't want to rekindle interest without being able to follow up on it.

If someone wants to take over maintenance I will gladly ramp them up on it new version.

**Comment by jsoverson** [comment]
supported by @devcrust in 1.6.0
